# Generated by Django 3.1.2 on 2021-01-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20210107_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
